############# English navigation ##############

# main menu
[[main]]
name = "Home"
pageRef = "/"
weight = 1

# [[main]]
# name = "About Us"
# pageRef = "/about"
# weight = 2

[[main]]
name = "Lab Work"
pageRef = "/categories/work"
weight = 3

[[main]]
name = "Blog"
pageRef = "/blog"
weight = 4

# footer menu
# [[footer]]
# name = "About"
# pageRef = "/about"
# weight = 1

# [[footer]]
# name = "Our work"
# pageRef = "/work"
# weight = 2

# [[footer]]
# name = "Privacy Policy"
# pageRef = "/privacy-policy"
# weight = 3
